<%-- Trang danh sách kệ do ShelfManagementServlet hiển thị; nhận shelfList, areas, bộ lọc, phân trang và flash. --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<c:set var="isManagePageAttr" value="true" scope="request"/><c:set var="activePage" value="shelf" scope="request"/><c:set var="pageTitle" value="Quản lý kệ sách – FPT Library" scope="request"/><c:set var="pageStylesheet" value="/assets/css/shelf-map.css" scope="request"/>
<%@ include file="/WEB-INF/views/fragments/header.jsp" %>
<main class="shelf-page"><section class="shelf-hero"><div><span>Quản lý kho sách</span><h1>Kệ sách</h1><p>Theo dõi sức chứa và vị trí của từng kệ.</p></div><strong>${totalShelves} kệ</strong></section>
<div class="shelf-content"><c:if test="${not empty flashSuccess}"><p class="shelf-alert success"><c:out value="${flashSuccess}"/></p></c:if><c:if test="${not empty flashError}"><p class="shelf-alert error"><c:out value="${flashError}"/></p></c:if>
<form class="shelf-filters" method="get" action="${pageContext.request.contextPath}${rolePath}/shelf"><input type="search" name="keyword" maxlength="100" value="${fn:escapeXml(keyword)}" placeholder="Tìm theo mã hoặc tên kệ..."><select name="area"><option value="">Tất cả khu vực</option><c:forEach var="area" items="${areas}"><option value="${fn:escapeXml(area)}" ${selectedArea eq area?'selected':''}><c:out value="${area}"/></option></c:forEach></select><select name="status"><option value="">Tất cả trạng thái</option><option value="ACTIVE" ${selectedStatus eq 'ACTIVE'?'selected':''}>Đang sử dụng</option><option value="INACTIVE" ${selectedStatus eq 'INACTIVE'?'selected':''}>Ngừng sử dụng</option></select><button class="btn btn-primary">Tìm kiếm</button></form>
<div class="shelf-toolbar"><p>Tổng cộng <strong>${totalShelves}</strong> kệ</p><div><a class="btn" href="${pageContext.request.contextPath}${rolePath}/shelf/map">Bản đồ kệ</a><a class="btn btn-primary" href="${pageContext.request.contextPath}${rolePath}/shelf/new">+ Thêm kệ sách</a></div></div>
<div class="shelf-table-wrap"><table class="shelf-table"><thead><tr><th>Mã kệ</th><th>Tên kệ</th><th>Khu vực / tầng</th><th>Số sách</th><th>Sức chứa</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:choose><c:when test="${empty shelfList}"><tr><td colspan="7" class="empty">Không tìm thấy kệ sách.</td></tr></c:when><c:otherwise><c:forEach var="shelf" items="${shelfList}"><tr><td><strong><c:out value="${shelf.code}"/></strong></td><td><c:out value="${shelf.name}"/></td><td><c:out value="${shelf.area}"/> · Tầng ${shelf.floorNumber}</td><td>${shelf.bookCount}</td><td>${shelf.capacity}</td><td><span class="badge ${shelf.status eq 'ACTIVE'?'active':'inactive'}">${shelf.status eq 'ACTIVE'?'Đang sử dụng':'Ngừng sử dụng'}</span></td><td class="actions"><a href="${pageContext.request.contextPath}${rolePath}/shelf/detail?id=${shelf.id}">Xem</a><a href="${pageContext.request.contextPath}${rolePath}/shelf/edit?id=${shelf.id}">Sửa</a><a href="${pageContext.request.contextPath}${rolePath}/shelf/map#shelf-${shelf.id}">Vị trí</a><form method="post" action="${pageContext.request.contextPath}${rolePath}/shelf/delete" data-delete-shelf><input type="hidden" name="id" value="${shelf.id}"><button type="submit">Xóa</button></form></td></tr></c:forEach></c:otherwise></c:choose></tbody></table></div>
<c:if test="${totalPages gt 1}"><nav class="shelf-pagination"><c:forEach begin="1" end="${totalPages}" var="page"><c:url var="pageUrl" value="${rolePath}/shelf"><c:param name="page" value="${page}"/><c:param name="keyword" value="${keyword}"/><c:param name="area" value="${selectedArea}"/><c:param name="status" value="${selectedStatus}"/></c:url><a class="${page eq currentPage?'current':''}" href="${pageUrl}">${page}</a></c:forEach></nav></c:if></div></main>
<script src="${pageContext.request.contextPath}/assets/js/shelf-map.js" defer></script><%@ include file="/WEB-INF/views/fragments/footer.jsp" %>
